### PR TITLE
Switch to new provisioning process

### PR DESCRIPTION
**Pull request by binford2k**
This switches us to using the new provisioner, as documented by https://confluence.puppetlabs.com/display/EDU/%28ALPHA%29+Self-provisioned+training+VMs

It means that if we want to release another old style VM that we'll have to build from the `legacy` branch. Going forward, we'll need to build the `master` VM by executing the `boostrap.sh` provisioning script in a first-boot task.

The `training` VM should be more or less unchanged, though it's reaching time to deprecate it and the legacy ILT workflow anyway.

### CODE REVIEW

**Comment by binford2k** [comment]
There are a few documentation files still to be updated, but otherwise ready for fingerpokin

**Comment by kjhenner** [comment]
@binford2k There are a couple of changes to profiles shared with the learning vm build. I'd like to have some time for testing before these changes are merged so I don't end up in a situation where I'm rushing to clean stuff up before a release. Just let me know when this is 'rc' level and I can run acceptance tests against the Learning VM.

The `require bootstrap::profile::pe_master` line in manifests/profile/cache_gems.pp might cause problems. Could you set up a parameter and/or conditional to manage that? Also, it looks like the gems are now kept in /var/cache/rubygems/gems instead of /var/cache/rubygems. Shouldn't be a big problem, but I'll have to double check that the configuration file on the Learning VM and nodes still points to the right place.

There are also some changes to manifests/profile/cache_rpms.pp, but on first glance it looks like the end-result should still be fine for the Learning VM. Does that sound right?

**Comment by binford2k** [comment]
@kjhenner  `$cache_dir` should be unchanged. I tried to change as little that wasn't necessary: https://github.com/puppetlabs/pltraining-bootstrap/pull/312/files#diff-937f336be1cd572a7ee82ca62954ac5bL6

What's the concern with `bootstrap::profile::pe_master`? You're installing PE on the learning VM, right? (although, the student VM also includes that profile, so we don't want to install PE there either)

**Comment by binford2k** [comment]
@kjhenner check the last commit. That should drop the PE dependency. I think the only reason it was in there is that Josh was piggybacking off the PE install.

**Comment by binford2k** [comment]
@kjhenner what do we need to do in order to test this with the LVM?

**Comment by binford2k** [comment]
ping @kjhenner

**Comment by binford2k** [comment]
@kjhenner can you switch the Jenkins build pipelines to use the `legacy` branch so we can get this merged while you determine how to validate it with the LVM?

**Comment by kjhenner** [comment]
@binford2k Sorry, I didn't see this! I'll have to check my notification preferences. We can go ahead and merge when you're ready, and I can run the builds against the legacy branch if needed.

**Comment by binford2k** [comment]
It's ready. (Not marked WIP).

**Pull request merged**
