### PR TITLE
Fix PE tuning on non-lvm builds

### PR DESCRIPTION
**Pull request by samuelson**

### CODE REVIEW

**Comment by binford2k** [comment]
Could this share work with https://github.com/puppetlabs/pltraining-classroom/blob/master/manifests/master/tuning.pp in some way? I wonder if we should split that into a separate module

**Comment by samuelson** [comment]
Hmm I'd forgotten about that. The problem is that the latest version of PE puts a redirect on port 80, so we need to disable it early if we want to use puppetfactory.

**Comment by samuelson** [comment]
@binford2k I think we should reconsider if we actually want to be managing that in the classroom module at all, so yeah maybe split it into another module.

**Comment by binford2k** [comment]
The idea originally was that someone like Gabe could tune it down to run on his tiny machine as needed, but that we could tune the defaults for someone with a more powerful machine. I don't think anyone ever used it in the field.

**Comment by binford2k** [comment]
@samuelson do we need to get this finished and merged before cutting a VM build?

**Comment by samuelson** [comment]
@binford2k only for 2017.2

**Comment by samuelson** [comment]
actually, not even that. That change is already in the repo

**Pull request closed without merging**
